### ISSUE TITLE
sync schema with current couper master branch

### ISSUE THREAD

**Issue by malud** [coupergateway/couper-vscode#135]
Ensure that we are up-to-date with the recent implementation.
E.g. TLS block or newly added functions.

**Comment by johakoch** [comment]
Which functions are missing? I searched the couper changelog for added functions. The last added to couper were
* trim() (in couper 1.11.0, added to vscode in https://github.com/coupergateway/couper-vscode/pull/112) and then
* contains(), join(), keys(), length(), lookup(), set_intersection(), to_number() (in couper 1.8.0, added to vscode in https://github.com/coupergateway/couper-vscode/pull/72).

**Comment by johakoch** [comment]
The `tls` blocks have different atributes or nested blocks depending on the parent block:
* In a `backend` block they can have _attributes_ according to https://docs.couper.io/configuration/block/backend_tls#attributes but _no nested blocks_.
* In a `server` block they can have _nested blocks_ according to https://docs.couper.io/configuration/block/server_tls#blocks but _no attributes_.

I don't think there's currently a way in the extension code to describe this.
@afflerbach Do you have an idea?

**Comment by afflerbach** [comment]
Different nested blocks should be doable with a solution like the [dynamic parents lookup for `beta_rate_limit`](/coupergateway/couper-vscode/blob/master/src/schema.js#L43).
For dynamic attribute completion, there's need for some similar function based logic [somewhere around here](/coupergateway/couper-vscode/blob/master/src/completion.js#L120).

**Comment by johakoch** [comment]
@afflerbach Looks like passing a function to `parents` also works for attributes :-)
